name: etri_00-05
dataset_type: kitti_odometry_velodyne
sequential: True
data:
  '00': '${KITTI_PATH}/odometry/00.lmdb'
  '01': '${KITTI_PATH}/odometry/01.lmdb'
  '02': '${KITTI_PATH}/odometry/02.lmdb'
  '03': '${KITTI_PATH}/odometry/03.lmdb'
  '04': '${KITTI_PATH}/odometry/04.lmdb'
  '05': '${KITTI_PATH}/odometry/05.lmdb'

