extends: 'deepclr_tf_base.yaml'

identifier: deepclr_tf_indy

data:
  training: ['${INDY_PATH}/odometry/00.lmdb']
  validation: ['${INDY_PATH}/odometry/00.lmdb']
  dataset_type: kitti_odometry_velodyne
  sequential: True

# transforms:
#   point_noise:
#     type: normal
#     scale: 0.01
#   translation_noise:
#     type: normal
#     scale: [0.2, 0.02, 0.02]
#   rotation_noise_deg:
#     type: normal
#     scale: [0.1, 0.1, 1.0]

transforms:
  point_noise:
    type: normal
    scale: 0.01
  translation_noise:
    type: normal
    scale: [0.02, 0.02, 0.02]
  rotation_noise_deg:
    type: normal
    scale: [0.05, 0.05, 0.05]