base_dir: /home/usrg/deepclr/models #'${MODEL_PATH}'
device: cuda

data_loader:
  parallel_loading: True
  num_workers: 6
  batch_size: 5
  buffer_size: 10

model:
  input_dim: 4
  point_dim: 3
  label_type: pose3d_dual_quat #pose3d_euler #pose3d_quat #pose3d_dual_quat,

  model_type: dlopvt
  params:
    batch_norm: False
    dropout: 1.0

    cloud_features:
      name: VoxelSetAbstraction #SetAbstraction
      params:
        BACKBONE_3D:
          NAME : VoxelBackBone8x

        PFE:
          NUM_POINT_FEATURES: 4
          POINT_CLOUD_RANGE: [-60.0, -40.0, -4, 60.0, 40.0, 2]
          VOXEL_SIZE: [0.2, 0.2, 0.1] #[0.05, 0.05, 0.1]
          MAX_POINTS_PER_VOXEL: 5
          MAX_NUMBER_OF_VOXELS: 60000
          POINT_SOURCE: raw_points
          NUM_KEYPOINTS: 1024
          NUM_OUTPUT_FEATURES: 128
          SAMPLE_METHOD: FPS
          FEATURES_SOURCE: ['x_conv1', 'x_conv2', 'raw_points']
          SA_LAYER:
              raw_points:
                  MLPS: [[16, 16], [16, 16]]
                  POOL_RADIUS: [0.4, 0.8]
                  NSAMPLE: [16, 16]
              x_conv1:
                  DOWNSAMPLE_FACTOR: 1
                  MLPS: [[16, 16], [16, 16]]
                  POOL_RADIUS: [0.4, 0.8]
                  NSAMPLE: [16, 16]
              x_conv2:
                  DOWNSAMPLE_FACTOR: 2
                  MLPS: [[32, 32], [32, 32]]
                  POOL_RADIUS: [0.8, 1.2]
                  NSAMPLE: [16, 32]
              x_conv3:
                  DOWNSAMPLE_FACTOR: 4
                  MLPS: [[64, 64], [64, 64]]
                  POOL_RADIUS: [1.2, 2.4]
                  NSAMPLE: [16, 32]
              x_conv4:
                  DOWNSAMPLE_FACTOR: 8
                  MLPS: [[64, 64], [64, 64]]
                  POOL_RADIUS: [2.4, 4.8]
                  NSAMPLE: [16, 32]

    merge:
      name: MotionEmbedding
      params:
        k: 20
        radius: 10.0 #3.0
        mlp: [128, 128, 256]

    transformer:
      name: Transformer
      params:
        transformer_dict :
          NUM_LAYER : 3
          NUM_HEAD :  4
          enc_nlayers : 3
          enc_dim : 256
          enc_nhead : 4
          enc_ffn_dim : 256
          enc_dropout : 0.1
          enc_activation : "relu"

          dec_nlayers : 3
          dec_dim : 256
          dec_nhead : 4
          dec_ffn_dim : 256
          dec_dropout : 0.1

          mlp_dropout : 0.1

        mlp: [256, 512, 1024] #[256, 256, 512, 512, 1024]
        linear: [1024, 512, 256]

    # output:
    #   name: OutputSimple
    #   params:
    #     mlp: [256, 512, 1024] #[256, 256, 512, 512, 1024]
    #     linear: [1024, 512, 256]

metrics:
  use_residual: False
  loss:
    - type: dual #trans
      weights: [5.0] #[1.0]
      params:
        p: 1 #2
    - type: rot
      weights: [200.0] #[200.0]
      params:
        p: 2
    - type: residual_rot
      weights: [2.0] #[200.0]
      params:
        p: 1

  other:
    - type: quat_norm #rot #quat_norm
    - type: dual_constraint #trans_3d #dual_constraint

optimizer:
  name: Ranger
  max_iterations: 800000
  base_lr: 0.0005
  weight_decay: 0.001
  bias_lr_factor: 2.0
  weight_decay_bias: 0.0
  accumulation_steps: 2

scheduler:
  name: CyclicLRWithFlatAndCosineAnnealing
  on_iteration: True
  on_validation: False
  needs_metrics: False
  params:
    cyclic_iterations: 600000
    flat_iterations: 100000
    annealing_iterations: 100000
    base_lr: 0.0000001
    max_lr: 0.0005
    step_size_up: 4000
    mode: triangular
    cycle_momentum: False

logging:
  add_graph: False
  summary_period: 20
  log_period: 200
  checkpoint_period: 24000 #40 : test valid#
  checkpoint_n_saved: 10
  validation_period: 24000 #40 : test valid#
  running_average_alpha: 0.001
